services:
  step-web:
    image: step-selfhosted:latest
    container_name: step-selfhosted
    command: ["run-step.sh"]
    ports:
      - "8989:8989"
    volumes:
      - ./data/homes:/opt/step/homes:Z
      # for custom web.xml files
      # - ./data/web.xml:/opt/step/step-web/WEB-INF/web.xml
